# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python39", "fontconfig", "dejavu_fonts", "liberation_ttf"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "fc-cache -fv"  # Refresh font cache
]

[start]
cmd = "python migrate_railway_db.py && gunicorn main:app"
