services:
  - type: web
    name: qr-business-cards
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
